theme = "catppuccin_mocha"

[editor]
shell = ["zsh", "-c"]
cursorline = false
color-modes = true
completion-trigger-len = 1
# bufferline = "multiple"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.lsp]
display-messages = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
"{" = ["goto_prev_paragraph"]
# "{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph"]
# "}" = ["goto_next_paragraph", "collapse_selection"]
X = "extend_line_above"

