theme = "catppuccin_mocha"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = false
color-modes = true
completion-trigger-len = 1

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.lsp]
display-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"X" = "extend_line_above"

# basically a shortcut for X_c
L = ["extend_to_line_bounds", "delete_selection_noyank", "open_above"]

"C-c" = "no_op"

[keys.normal.space]
"c" = "toggle_comments"
