theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
color-modes = true
completion-trigger-len = 1
idle-timeout = 0

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.lsp]
display-messages = true
snippets = false
display-inlay-hints = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"
tabpad = "."

[editor.whitespace.characters]
tab = "→"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"C-6" = ["goto_last_accessed_file"]

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
H = ":toggle lsp.display-inlay-hints"

[keys.insert]
C-h = "delete_char_backward" # Most terminals do this by default.
C-l = "move_char_right" # Useful to jump over closing parenthesis.
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
