theme = "catppuccin_mocha"

[editor]
# line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
color-modes = true
completion-trigger-len = 1
# bufferline = "multiple"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
X = "extend_line_above"
"m" = "select_textobject_inner"
"M" = "select_textobject_around"

# Currently broken
# C-c = "no_op"
# "C-/" = "toggle_comments"
