theme = "catppuccin_frappe"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
color-modes = true
completion-trigger-len = 1
idle-timeout = 0
bufferline = "multiple"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.lsp]
display-messages = true
snippets = false
display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"#" = "toggle_comments"
